services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: pdf-processor-api
    container_name: pdf-processor-api
    command: ./run-api.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
      - valkey
    volumes:
      - uploads_data:/mnt/uploads

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    image: pdf-processor-worker
    container_name: pdf-processor-worker
    env_file:
      - .env
    depends_on:
      - mongo
      - valkey
      - api
    volumes:
      - uploads_data:/mnt/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: pdf-processor-frontend
    container_name: pdf-processor-frontend
    ports:
      - "80:80"
    depends_on:
      - api

  mongo:
    image: mongo:7
    restart: unless-stopped
    container_name: pdf-processor-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  valkey:
    image: valkey/valkey:8
    restart: unless-stopped
    container_name: pdf-processor-valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data

volumes:
  mongo_data:
  valkey_data:
  uploads_data:
